### ISSUE TITLE
mariadb host naming

### ISSUE THREAD

**Issue by doormat18** [ibm-cloud-architecture/refarch-cloudnative-micro-orders#94]
For the orders chart, the mariadb host name is hard-coded to orders-mariadb-orders-mariadb which works fine for the project. However, when orders microservice is included in the larger bluecompute-ce chart this breaks as the mariadb host will be named bluecompute-ce-orders-mariadb.

**Comment by kevinwlau** [comment]
Thanks for bringing this up, I'll look into it.

Is this on the `spring` branch, @doormat18 ?
